// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///    options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDZR8I4Q5oJ3IvfY5EA4Bk-RNqtlnYWwo',
    appId: '1:422589866231:web:f2045ea065c5587a0473f2',
    messagingSenderId: '422589866231',
    projectId: 'file-converter-app-7e11d',
    authDomain: 'file-converter-app-7e11d.firebaseapp.com',
    storageBucket: 'file-converter-app-7e11d.firebasestorage.app',
    measurementId: 'G-7VB2NJ9BBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD07-_sDin4tPMtHohWs6Zn3CJL9Szny9o',
    appId: '1:422589866231:android:97c38fad00b473d60473f2',
    messagingSenderId: '422589866231',
    projectId: 'file-converter-app-7e11d',
    storageBucket: 'file-converter-app-7e11d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdZ-iDSjDm1XDduE_dE50A6fjso0n6tVU',
    appId: '1:422589866231:ios:545a98a66dfaa4c10473f2',
    messagingSenderId: '422589866231',
    projectId: 'file-converter-app-7e11d',
    storageBucket: 'file-converter-app-7e11d.firebasestorage.app',
    iosBundleId: 'com.konvert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdZ-iDSjDm1XDduE_dE50A6fjso0n6tVU',
    appId: '1:422589866231:ios:545a98a66dfaa4c10473f2',
    messagingSenderId: '422589866231',
    projectId: 'file-converter-app-7e11d',
    storageBucket: 'file-converter-app-7e11d.firebasestorage.app',
    iosBundleId: 'com.konvert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDZR8I4Q5oJ3IvfY5EA4Bk-RNqtlnYWwo',
    appId: '1:422589866231:web:7230d54fac48b77a0473f2',
    messagingSenderId: '422589866231',
    projectId: 'file-converter-app-7e11d',
    authDomain: 'file-converter-app-7e11d.firebaseapp.com',
    storageBucket: 'file-converter-app-7e11d.firebasestorage.app',
    measurementId: 'G-Z431DW0GVY',
  );
}
